name: CI Notice

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # main
      
      - uses: actions-cool/ci-notice@cfdbfac7f0a65d8e7a15306717b59f4bc6078bc8 # main
        with:
          ci: |
            yarn
            npm run package
          notice-types: 'issue'
          issue-assignees: 'xrkffgg'
