name: CI Notice

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # main
      
      - uses: actions-cool/ci-notice@cfdbfac7f0a65d8e7a15306717b59f4bc6078bc8 # main
        with:
          ci: |
            npm install
            npm run package
          notice-types: 'issue'
          issue-assignees: 'xrkffgg'
