name: CI

on: [push, pull_request]

permissions: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # main

      - name: install
        run: yarn install
      
      - name: format-check
        run: yarn format-check

      - name: package
        run: yarn package
