name: CI

on: [push, pull_request]

permissions: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # main

      - name: install
        run: yarn install
      
      - name: all
        run: yarn all
